/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.1.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.nextworks.openapi.msno.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.nextworks.openapi.msno.model.ExtVirtualLinkInfo;
import it.nextworks.openapi.msno.model.ModifyVnfInfoData;

import java.io.IOException;

/**
 * Information about the changed VNF instance information, including VNF configurable properties,if applicable. When the \&quot;changedInfo\&quot; attribute is present, either the \&quot;changedVnfInfo\&quot; attribute or the \&quot;changedExtConnectivity\&quot; attribute or both shall be present. 
 */
@ApiModel(description = "Information about the changed VNF instance information, including VNF configurable properties,if applicable. When the \"changedInfo\" attribute is present, either the \"changedVnfInfo\" attribute or the \"changedExtConnectivity\" attribute or both shall be present. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-08T16:52:33.422+01:00")
public class AffectedVnfChangedInfo {
  @SerializedName("changedVnfInfo")
  private ModifyVnfInfoData changedVnfInfo = null;

  @SerializedName("changedExtConnectivity")
  private ExtVirtualLinkInfo changedExtConnectivity = null;

  public AffectedVnfChangedInfo changedVnfInfo(ModifyVnfInfoData changedVnfInfo) {
    this.changedVnfInfo = changedVnfInfo;
    return this;
  }

   /**
   * Information about the changed VNF instance information, including configurable properties, if applicable. 
   * @return changedVnfInfo
  **/
  @ApiModelProperty(value = "Information about the changed VNF instance information, including configurable properties, if applicable. ")
  public ModifyVnfInfoData getChangedVnfInfo() {
    return changedVnfInfo;
  }

  public void setChangedVnfInfo(ModifyVnfInfoData changedVnfInfo) {
    this.changedVnfInfo = changedVnfInfo;
  }

  public AffectedVnfChangedInfo changedExtConnectivity(ExtVirtualLinkInfo changedExtConnectivity) {
    this.changedExtConnectivity = changedExtConnectivity;
    return this;
  }

   /**
   * Information about changed external connectivity, if applicable. 
   * @return changedExtConnectivity
  **/
  @ApiModelProperty(value = "Information about changed external connectivity, if applicable. ")
  public ExtVirtualLinkInfo getChangedExtConnectivity() {
    return changedExtConnectivity;
  }

  public void setChangedExtConnectivity(ExtVirtualLinkInfo changedExtConnectivity) {
    this.changedExtConnectivity = changedExtConnectivity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AffectedVnfChangedInfo affectedVnfChangedInfo = (AffectedVnfChangedInfo) o;
    return Objects.equals(this.changedVnfInfo, affectedVnfChangedInfo.changedVnfInfo) &&
        Objects.equals(this.changedExtConnectivity, affectedVnfChangedInfo.changedExtConnectivity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changedVnfInfo, changedExtConnectivity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AffectedVnfChangedInfo {\n");
    
    sb.append("    changedVnfInfo: ").append(toIndentedString(changedVnfInfo)).append("\n");
    sb.append("    changedExtConnectivity: ").append(toIndentedString(changedExtConnectivity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

