/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.1.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.nextworks.openapi.msno.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.nextworks.openapi.msno.model.ExtLinkPortData;
import it.nextworks.openapi.msno.model.VnfExtCpData;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This type represents an external VL. It shall comply with the provisions defined in Table 6.5.3.26-1. 
 */
@ApiModel(description = "This type represents an external VL. It shall comply with the provisions defined in Table 6.5.3.26-1. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-08T16:52:33.422+01:00")
public class ExtVirtualLinkData {
  @SerializedName("extVirtualLinkId")
  private String extVirtualLinkId = null;

  @SerializedName("vimId")
  private String vimId = null;

  @SerializedName("resourceProviderId")
  private String resourceProviderId = null;

  @SerializedName("resourceId")
  private String resourceId = null;

  @SerializedName("extCps")
  private List<VnfExtCpData> extCps = new ArrayList<VnfExtCpData>();

  @SerializedName("extLinkPorts")
  private List<ExtLinkPortData> extLinkPorts = null;

  public ExtVirtualLinkData extVirtualLinkId(String extVirtualLinkId) {
    this.extVirtualLinkId = extVirtualLinkId;
    return this;
  }

   /**
   * The identifier of the external VL instance, if provided. 
   * @return extVirtualLinkId
  **/
  @ApiModelProperty(value = "The identifier of the external VL instance, if provided. ")
  public String getExtVirtualLinkId() {
    return extVirtualLinkId;
  }

  public void setExtVirtualLinkId(String extVirtualLinkId) {
    this.extVirtualLinkId = extVirtualLinkId;
  }

  public ExtVirtualLinkData vimId(String vimId) {
    this.vimId = vimId;
    return this;
  }

   /**
   * Identifier of the VIM that manages this resource. This attribute shall only be supported and present if VNFrelated resource management in direct mode is applicable. 
   * @return vimId
  **/
  @ApiModelProperty(value = "Identifier of the VIM that manages this resource. This attribute shall only be supported and present if VNFrelated resource management in direct mode is applicable. ")
  public String getVimId() {
    return vimId;
  }

  public void setVimId(String vimId) {
    this.vimId = vimId;
  }

  public ExtVirtualLinkData resourceProviderId(String resourceProviderId) {
    this.resourceProviderId = resourceProviderId;
    return this;
  }

   /**
   * Identifies the entity responsible for the management of this resource. This attribute shall only be supported and present if VNF-related resource management in indirect mode is applicable. The identification scheme is outside the scope of the present document. 
   * @return resourceProviderId
  **/
  @ApiModelProperty(value = "Identifies the entity responsible for the management of this resource. This attribute shall only be supported and present if VNF-related resource management in indirect mode is applicable. The identification scheme is outside the scope of the present document. ")
  public String getResourceProviderId() {
    return resourceProviderId;
  }

  public void setResourceProviderId(String resourceProviderId) {
    this.resourceProviderId = resourceProviderId;
  }

  public ExtVirtualLinkData resourceId(String resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * The identifier of the resource in the scope of the VIM or the resource provider. 
   * @return resourceId
  **/
  @ApiModelProperty(required = true, value = "The identifier of the resource in the scope of the VIM or the resource provider. ")
  public String getResourceId() {
    return resourceId;
  }

  public void setResourceId(String resourceId) {
    this.resourceId = resourceId;
  }

  public ExtVirtualLinkData extCps(List<VnfExtCpData> extCps) {
    this.extCps = extCps;
    return this;
  }

  public ExtVirtualLinkData addExtCpsItem(VnfExtCpData extCpsItem) {
    this.extCps.add(extCpsItem);
    return this;
  }

   /**
   * External CPs of the VNF to be connected to this external VL. 
   * @return extCps
  **/
  @ApiModelProperty(required = true, value = "External CPs of the VNF to be connected to this external VL. ")
  public List<VnfExtCpData> getExtCps() {
    return extCps;
  }

  public void setExtCps(List<VnfExtCpData> extCps) {
    this.extCps = extCps;
  }

  public ExtVirtualLinkData extLinkPorts(List<ExtLinkPortData> extLinkPorts) {
    this.extLinkPorts = extLinkPorts;
    return this;
  }

  public ExtVirtualLinkData addExtLinkPortsItem(ExtLinkPortData extLinkPortsItem) {
    if (this.extLinkPorts == null) {
      this.extLinkPorts = new ArrayList<ExtLinkPortData>();
    }
    this.extLinkPorts.add(extLinkPortsItem);
    return this;
  }

   /**
   * Externally provided link ports to be used to connect external connection points to this external VL. 
   * @return extLinkPorts
  **/
  @ApiModelProperty(value = "Externally provided link ports to be used to connect external connection points to this external VL. ")
  public List<ExtLinkPortData> getExtLinkPorts() {
    return extLinkPorts;
  }

  public void setExtLinkPorts(List<ExtLinkPortData> extLinkPorts) {
    this.extLinkPorts = extLinkPorts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtVirtualLinkData extVirtualLinkData = (ExtVirtualLinkData) o;
    return Objects.equals(this.extVirtualLinkId, extVirtualLinkData.extVirtualLinkId) &&
        Objects.equals(this.vimId, extVirtualLinkData.vimId) &&
        Objects.equals(this.resourceProviderId, extVirtualLinkData.resourceProviderId) &&
        Objects.equals(this.resourceId, extVirtualLinkData.resourceId) &&
        Objects.equals(this.extCps, extVirtualLinkData.extCps) &&
        Objects.equals(this.extLinkPorts, extVirtualLinkData.extLinkPorts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extVirtualLinkId, vimId, resourceProviderId, resourceId, extCps, extLinkPorts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtVirtualLinkData {\n");
    
    sb.append("    extVirtualLinkId: ").append(toIndentedString(extVirtualLinkId)).append("\n");
    sb.append("    vimId: ").append(toIndentedString(vimId)).append("\n");
    sb.append("    resourceProviderId: ").append(toIndentedString(resourceProviderId)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    extCps: ").append(toIndentedString(extCps)).append("\n");
    sb.append("    extLinkPorts: ").append(toIndentedString(extLinkPorts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

