/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.1.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.nextworks.openapi.msno.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The enumeration LcmOpNameForChangeNotificationType represents the name of the lifecycle operation that impacts the NS component and trigger an NS change notification. It shall comply with the provisions defined in Table 6.5.4.6-1. Value | Description ------|------------ VNF_INSTANTIATE | Represents the \&quot;Instantiate VNF\&quot; LCM operation. VNF_SCALE | Represents the \&quot;Scale VNF\&quot; LCM operation. VNF_SCALE_TO_LEVEL | Represents the \&quot;Scale VNF to Level\&quot; LCM operation. VNF_CHANGE_FLAVOUR | Represents the \&quot;Change VNF Flavor\&quot; LCM operation. VNF_TERMINATE | Represents the \&quot;Terminate VNF\&quot; LCM operation. VNF_HEAL | Represents the \&quot;Heal VNF\&quot; LCM operation. VNF_OPERATE | Represents the \&quot;Operate VNF\&quot; LCM operation. VNF_CHANGE_EXT_CONN | Represents the \&quot;Change external VNF connectivity\&quot; LCM operation. VNF_MODIFY_INFO | Represents the \&quot;Modify VNF Information\&quot; LCM operation. NS_INSTANTIATE | Represents the \&quot;Instantiate NS\&quot; LCM operation NS_SCALE | Represents the \&quot;Scale NS\&quot; LCM operation. NS_UPDATE | Represents the \&quot;Update NS\&quot; LCM operation. NS_TERMINATE | Represents the \&quot;Terminate NS\&quot; LCM operation. NS_HEAL | Represents the \&quot;Heal NS\&quot; LCM operation. 
 */
@JsonAdapter(LcmOpNameForChangeNotificationType.Adapter.class)
public enum LcmOpNameForChangeNotificationType {
  
  VNF_INSTANTIATE("VNF_INSTANTIATE"),
  
  VNF_SCALE("VNF_SCALE"),
  
  VNF_SCALE_TO_LEVEL("VNF_SCALE_TO_LEVEL"),
  
  VNF_CHANGE_FLAVOUR("VNF_CHANGE_FLAVOUR"),
  
  VNF_TERMINATE("VNF_TERMINATE"),
  
  VNF_HEAL("VNF_HEAL"),
  
  VNF_OPERATE("VNF_OPERATE"),
  
  VNF_CHANGE_EXT_CONN("VNF_CHANGE_EXT_CONN"),
  
  VNF_MODIFY_INFO("VNF_MODIFY_INFO"),
  
  NS_INSTANTIATE("NS_INSTANTIATE"),
  
  NS_SCALE("NS_SCALE"),
  
  NS_UPDATE("NS_UPDATE"),
  
  NS_TERMINATE("NS_TERMINATE"),
  
  NS_HEAL("NS_HEAL");

  private String value;

  LcmOpNameForChangeNotificationType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LcmOpNameForChangeNotificationType fromValue(String text) {
    for (LcmOpNameForChangeNotificationType b : LcmOpNameForChangeNotificationType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<LcmOpNameForChangeNotificationType> {
    @Override
    public void write(final JsonWriter jsonWriter, final LcmOpNameForChangeNotificationType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LcmOpNameForChangeNotificationType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LcmOpNameForChangeNotificationType.fromValue(String.valueOf(value));
    }
  }
}

