/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.1.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.nextworks.openapi.msno.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.nextworks.openapi.msno.model.AffectedNs;
import it.nextworks.openapi.msno.model.AffectedPnf;
import it.nextworks.openapi.msno.model.AffectedSap;
import it.nextworks.openapi.msno.model.AffectedVl;
import it.nextworks.openapi.msno.model.AffectedVnf;
import it.nextworks.openapi.msno.model.AffectedVnffg;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This attribute contains information about the cumulative changes to virtualised resources that were performed so far by the LCM operation since its start, if applicable 
 */
@ApiModel(description = "This attribute contains information about the cumulative changes to virtualised resources that were performed so far by the LCM operation since its start, if applicable ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-08T16:52:33.422+01:00")
public class NsLcmOpOccResourceChanges {
  @SerializedName("affectedVnfs")
  private List<AffectedVnf> affectedVnfs = null;

  @SerializedName("affectedPnfs")
  private List<AffectedPnf> affectedPnfs = null;

  @SerializedName("affectedVls")
  private List<AffectedVl> affectedVls = null;

  @SerializedName("affectedVnffgs")
  private List<AffectedVnffg> affectedVnffgs = null;

  @SerializedName("affectedNss")
  private List<AffectedNs> affectedNss = null;

  @SerializedName("affectedSaps")
  private List<AffectedSap> affectedSaps = null;

  public NsLcmOpOccResourceChanges affectedVnfs(List<AffectedVnf> affectedVnfs) {
    this.affectedVnfs = affectedVnfs;
    return this;
  }

  public NsLcmOpOccResourceChanges addAffectedVnfsItem(AffectedVnf affectedVnfsItem) {
    if (this.affectedVnfs == null) {
      this.affectedVnfs = new ArrayList<AffectedVnf>();
    }
    this.affectedVnfs.add(affectedVnfsItem);
    return this;
  }

   /**
   * Information about the VNF instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. 
   * @return affectedVnfs
  **/
  @ApiModelProperty(value = "Information about the VNF instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. ")
  public List<AffectedVnf> getAffectedVnfs() {
    return affectedVnfs;
  }

  public void setAffectedVnfs(List<AffectedVnf> affectedVnfs) {
    this.affectedVnfs = affectedVnfs;
  }

  public NsLcmOpOccResourceChanges affectedPnfs(List<AffectedPnf> affectedPnfs) {
    this.affectedPnfs = affectedPnfs;
    return this;
  }

  public NsLcmOpOccResourceChanges addAffectedPnfsItem(AffectedPnf affectedPnfsItem) {
    if (this.affectedPnfs == null) {
      this.affectedPnfs = new ArrayList<AffectedPnf>();
    }
    this.affectedPnfs.add(affectedPnfsItem);
    return this;
  }

   /**
   * Information about the PNF instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. 
   * @return affectedPnfs
  **/
  @ApiModelProperty(value = "Information about the PNF instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. ")
  public List<AffectedPnf> getAffectedPnfs() {
    return affectedPnfs;
  }

  public void setAffectedPnfs(List<AffectedPnf> affectedPnfs) {
    this.affectedPnfs = affectedPnfs;
  }

  public NsLcmOpOccResourceChanges affectedVls(List<AffectedVl> affectedVls) {
    this.affectedVls = affectedVls;
    return this;
  }

  public NsLcmOpOccResourceChanges addAffectedVlsItem(AffectedVl affectedVlsItem) {
    if (this.affectedVls == null) {
      this.affectedVls = new ArrayList<AffectedVl>();
    }
    this.affectedVls.add(affectedVlsItem);
    return this;
  }

   /**
   * Information about the VL instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. 
   * @return affectedVls
  **/
  @ApiModelProperty(value = "Information about the VL instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. ")
  public List<AffectedVl> getAffectedVls() {
    return affectedVls;
  }

  public void setAffectedVls(List<AffectedVl> affectedVls) {
    this.affectedVls = affectedVls;
  }

  public NsLcmOpOccResourceChanges affectedVnffgs(List<AffectedVnffg> affectedVnffgs) {
    this.affectedVnffgs = affectedVnffgs;
    return this;
  }

  public NsLcmOpOccResourceChanges addAffectedVnffgsItem(AffectedVnffg affectedVnffgsItem) {
    if (this.affectedVnffgs == null) {
      this.affectedVnffgs = new ArrayList<AffectedVnffg>();
    }
    this.affectedVnffgs.add(affectedVnffgsItem);
    return this;
  }

   /**
   * Information about the VNFFG instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. See note 
   * @return affectedVnffgs
  **/
  @ApiModelProperty(value = "Information about the VNFFG instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. See note ")
  public List<AffectedVnffg> getAffectedVnffgs() {
    return affectedVnffgs;
  }

  public void setAffectedVnffgs(List<AffectedVnffg> affectedVnffgs) {
    this.affectedVnffgs = affectedVnffgs;
  }

  public NsLcmOpOccResourceChanges affectedNss(List<AffectedNs> affectedNss) {
    this.affectedNss = affectedNss;
    return this;
  }

  public NsLcmOpOccResourceChanges addAffectedNssItem(AffectedNs affectedNssItem) {
    if (this.affectedNss == null) {
      this.affectedNss = new ArrayList<AffectedNs>();
    }
    this.affectedNss.add(affectedNssItem);
    return this;
  }

   /**
   * Information about the nested NS instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. See note. 
   * @return affectedNss
  **/
  @ApiModelProperty(value = "Information about the nested NS instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. See note. ")
  public List<AffectedNs> getAffectedNss() {
    return affectedNss;
  }

  public void setAffectedNss(List<AffectedNs> affectedNss) {
    this.affectedNss = affectedNss;
  }

  public NsLcmOpOccResourceChanges affectedSaps(List<AffectedSap> affectedSaps) {
    this.affectedSaps = affectedSaps;
    return this;
  }

  public NsLcmOpOccResourceChanges addAffectedSapsItem(AffectedSap affectedSapsItem) {
    if (this.affectedSaps == null) {
      this.affectedSaps = new ArrayList<AffectedSap>();
    }
    this.affectedSaps.add(affectedSapsItem);
    return this;
  }

   /**
   * Information about the nested NS instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. See note. 
   * @return affectedSaps
  **/
  @ApiModelProperty(value = "Information about the nested NS instances that were affected during the lifecycle operation, if this notification represents the result of a lifecycle operation. See note. ")
  public List<AffectedSap> getAffectedSaps() {
    return affectedSaps;
  }

  public void setAffectedSaps(List<AffectedSap> affectedSaps) {
    this.affectedSaps = affectedSaps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsLcmOpOccResourceChanges nsLcmOpOccResourceChanges = (NsLcmOpOccResourceChanges) o;
    return Objects.equals(this.affectedVnfs, nsLcmOpOccResourceChanges.affectedVnfs) &&
        Objects.equals(this.affectedPnfs, nsLcmOpOccResourceChanges.affectedPnfs) &&
        Objects.equals(this.affectedVls, nsLcmOpOccResourceChanges.affectedVls) &&
        Objects.equals(this.affectedVnffgs, nsLcmOpOccResourceChanges.affectedVnffgs) &&
        Objects.equals(this.affectedNss, nsLcmOpOccResourceChanges.affectedNss) &&
        Objects.equals(this.affectedSaps, nsLcmOpOccResourceChanges.affectedSaps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(affectedVnfs, affectedPnfs, affectedVls, affectedVnffgs, affectedNss, affectedSaps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsLcmOpOccResourceChanges {\n");
    
    sb.append("    affectedVnfs: ").append(toIndentedString(affectedVnfs)).append("\n");
    sb.append("    affectedPnfs: ").append(toIndentedString(affectedPnfs)).append("\n");
    sb.append("    affectedVls: ").append(toIndentedString(affectedVls)).append("\n");
    sb.append("    affectedVnffgs: ").append(toIndentedString(affectedVnffgs)).append("\n");
    sb.append("    affectedNss: ").append(toIndentedString(affectedNss)).append("\n");
    sb.append("    affectedSaps: ").append(toIndentedString(affectedSaps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

