/*
 * SOL005 - NS Lifecycle Management Interface
 * SOL005 - NS Lifecycle Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 1.1.0-impl:etsi.org:ETSI_NFV_OpenAPI:1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.nextworks.openapi.msno.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.nextworks.openapi.msno.model.CpProtocolInfo;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This type represents an SAP instance. It shall comply with the provisions defined in Table 6.5.3.67-1. 
 */
@ApiModel(description = "This type represents an SAP instance. It shall comply with the provisions defined in Table 6.5.3.67-1. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-08T16:52:33.422+01:00")
public class SapInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("sapdId")
  private String sapdId = null;

  @SerializedName("sapName")
  private String sapName = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("sapProtocolInfo")
  private List<CpProtocolInfo> sapProtocolInfo = new ArrayList<CpProtocolInfo>();

  public SapInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identifier of the SAP instance. 
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Identifier of the SAP instance. ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SapInfo sapdId(String sapdId) {
    this.sapdId = sapdId;
    return this;
  }

   /**
   * Identifier of the SAPD in the NSD. 
   * @return sapdId
  **/
  @ApiModelProperty(required = true, value = "Identifier of the SAPD in the NSD. ")
  public String getSapdId() {
    return sapdId;
  }

  public void setSapdId(String sapdId) {
    this.sapdId = sapdId;
  }

  public SapInfo sapName(String sapName) {
    this.sapName = sapName;
    return this;
  }

   /**
   * Human readable name for the SAP instance. 
   * @return sapName
  **/
  @ApiModelProperty(required = true, value = "Human readable name for the SAP instance. ")
  public String getSapName() {
    return sapName;
  }

  public void setSapName(String sapName) {
    this.sapName = sapName;
  }

  public SapInfo description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Human readable description for the SAP instance. 
   * @return description
  **/
  @ApiModelProperty(value = "Human readable description for the SAP instance. ")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SapInfo sapProtocolInfo(List<CpProtocolInfo> sapProtocolInfo) {
    this.sapProtocolInfo = sapProtocolInfo;
    return this;
  }

  public SapInfo addSapProtocolInfoItem(CpProtocolInfo sapProtocolInfoItem) {
    this.sapProtocolInfo.add(sapProtocolInfoItem);
    return this;
  }

   /**
   * Network protocol information for this SAP. 
   * @return sapProtocolInfo
  **/
  @ApiModelProperty(required = true, value = "Network protocol information for this SAP. ")
  public List<CpProtocolInfo> getSapProtocolInfo() {
    return sapProtocolInfo;
  }

  public void setSapProtocolInfo(List<CpProtocolInfo> sapProtocolInfo) {
    this.sapProtocolInfo = sapProtocolInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapInfo sapInfo = (SapInfo) o;
    return Objects.equals(this.id, sapInfo.id) &&
        Objects.equals(this.sapdId, sapInfo.sapdId) &&
        Objects.equals(this.sapName, sapInfo.sapName) &&
        Objects.equals(this.description, sapInfo.description) &&
        Objects.equals(this.sapProtocolInfo, sapInfo.sapProtocolInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sapdId, sapName, description, sapProtocolInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sapdId: ").append(toIndentedString(sapdId)).append("\n");
    sb.append("    sapName: ").append(toIndentedString(sapName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    sapProtocolInfo: ").append(toIndentedString(sapProtocolInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

