/*
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.mda.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ContextModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-03T17:13:21.498+02:00[Europe/Rome]")
public class ContextModel {
  @SerializedName("resource_id")
  private String resourceId = null;

  @SerializedName("network_slice_id")
  private String networkSliceId = null;

  @SerializedName("parent_id")
  private String parentId = null;

  public ContextModel resourceId(String resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @Schema(required = true, description = "")
  public String getResourceId() {
    return resourceId;
  }

  public void setResourceId(String resourceId) {
    this.resourceId = resourceId;
  }

  public ContextModel networkSliceId(String networkSliceId) {
    this.networkSliceId = networkSliceId;
    return this;
  }

   /**
   * Get networkSliceId
   * @return networkSliceId
  **/
  @Schema(required = true, description = "")
  public String getNetworkSliceId() {
    return networkSliceId;
  }

  public void setNetworkSliceId(String networkSliceId) {
    this.networkSliceId = networkSliceId;
  }

  public ContextModel parentId(String parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @Schema(required = true, description = "")
  public String getParentId() {
    return parentId;
  }

  public void setParentId(String parentId) {
    this.parentId = parentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContextModel contextModel = (ContextModel) o;
    return Objects.equals(this.resourceId, contextModel.resourceId) &&
        Objects.equals(this.networkSliceId, contextModel.networkSliceId) &&
        Objects.equals(this.parentId, contextModel.parentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceId, networkSliceId, parentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContextModel {\n");
    
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    networkSliceId: ").append(toIndentedString(networkSliceId)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
