/*
 * 5GZorro eLicense Manager Core Swagger
 * Swagger 5GZorro for the centralized eLicense Manager System of the project
 *
 * OpenAPI spec version: 0.1.0
 * Contact: guillermo.gomez.external@atos.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.elma.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * CheckLicensing
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-10T18:02:02.820+01:00[Europe/Rome]")
public class CheckLicensing {
  @SerializedName("productID")
  private String productID = null;

  @SerializedName("domains")
  private List<Domains> domains = new ArrayList<Domains>();

  public CheckLicensing productID(String productID) {
    this.productID = productID;
    return this;
  }

   /**
   * Get productID
   * @return productID
  **/
  @Schema(required = true, description = "")
  public String getProductID() {
    return productID;
  }

  public void setProductID(String productID) {
    this.productID = productID;
  }

  public CheckLicensing domains(List<Domains> domains) {
    this.domains = domains;
    return this;
  }

  public CheckLicensing addDomainsItem(Domains domainsItem) {
    this.domains.add(domainsItem);
    return this;
  }

   /**
   * list of domains where the PO may be used
   * @return domains
  **/
  @Schema(required = true, description = "list of domains where the PO may be used")
  public List<Domains> getDomains() {
    return domains;
  }

  public void setDomains(List<Domains> domains) {
    this.domains = domains;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckLicensing checkLicensing = (CheckLicensing) o;
    return Objects.equals(this.productID, checkLicensing.productID) &&
        Objects.equals(this.domains, checkLicensing.domains);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productID, domains);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckLicensing {\n");
    
    sb.append("    productID: ").append(toIndentedString(productID)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
