/*
 * 5GZorro eLicense Manager Core Swagger
 * Swagger 5GZorro for the centralized eLicense Manager System of the project
 *
 * OpenAPI spec version: 0.1.0
 * Contact: guillermo.gomez.external@atos.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.elma.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * Domains
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-10T18:02:02.820+01:00[Europe/Rome]")
public class Domains {
  @SerializedName("domainDID")
  private String domainDID = null;

  @SerializedName("nst_id")
  private String nstId = null;

  @SerializedName("nsd")
  private List<String> nsd = new ArrayList<String>();

  public Domains domainDID(String domainDID) {
    this.domainDID = domainDID;
    return this;
  }

   /**
   * Get domainDID
   * @return domainDID
  **/
  @Schema(required = true, description = "")
  public String getDomainDID() {
    return domainDID;
  }

  public void setDomainDID(String domainDID) {
    this.domainDID = domainDID;
  }

  public Domains nstId(String nstId) {
    this.nstId = nstId;
    return this;
  }

   /**
   * Get nstId
   * @return nstId
  **/
  @Schema(required = true, description = "")
  public String getNstId() {
    return nstId;
  }

  public void setNstId(String nstId) {
    this.nstId = nstId;
  }

  public Domains nsd(List<String> nsd) {
    this.nsd = nsd;
    return this;
  }

  public Domains addNsdItem(String nsdItem) {
    this.nsd.add(nsdItem);
    return this;
  }

   /**
   * list of Network Service Descriptors which are bound by the PO
   * @return nsd
  **/
  @Schema(required = true, description = "list of Network Service Descriptors which are bound by the PO")
  public List<String> getNsd() {
    return nsd;
  }

  public void setNsd(List<String> nsd) {
    this.nsd = nsd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Domains domains = (Domains) o;
    return Objects.equals(this.domainDID, domains.domainDID) &&
        Objects.equals(this.nstId, domains.nstId) &&
        Objects.equals(this.nsd, domains.nsd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domainDID, nstId, nsd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Domains {\n");
    
    sb.append("    domainDID: ").append(toIndentedString(domainDID)).append("\n");
    sb.append("    nstId: ").append(toIndentedString(nstId)).append("\n");
    sb.append("    nsd: ").append(toIndentedString(nsd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
