/*
 * OSM NB API featuring ETSI NFV SOL005
 * This is Open Source MANO Northbound API featuring ETSI NFV SOL005. For more information on OSM, you can visit [http://osm.etsi.org](http://osm.etsi.org). You can send us your comments and questions to OSM_TECH@list.etsi.org or join the [OpenSourceMANO Slack Workplace](https://join.slack.com/t/opensourcemano/shared_invite/enQtMzQ3MzYzNTQ0NDIyLWVkNTE4ZjZjNWI0ZTQyN2VhOTI1MjViMzU1NWYwMWM3ODI4NTQyY2VlODA2ZjczMWIyYTFkZWNiZmFkM2M2ZDk) 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: OSM_TECH@list.etsi.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.NsiLcmOpOccLinks;
import io.swagger.client.model.NsiLcmOpOccOperationParams;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;
/**
 * NsiLcmOpOcc
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-04T13:03:17.599+01:00[Europe/Rome]")
public class NsiLcmOpOcc {
  @SerializedName("_id")
  private UUID _id = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("lcmOperationType")
  private String lcmOperationType = null;

  @SerializedName("netsliceInstanceId")
  private UUID netsliceInstanceId = null;

  @SerializedName("isAutomaticInvocation")
  private Boolean isAutomaticInvocation = null;

  @SerializedName("isCancelPending")
  private Boolean isCancelPending = null;

  @SerializedName("startTime")
  private Float startTime = null;

  @SerializedName("statusEnteredTime")
  private Float statusEnteredTime = null;

  @SerializedName("operationParams")
  private NsiLcmOpOccOperationParams operationParams = null;

  @SerializedName("operationState")
  private String operationState = null;

  @SerializedName("detailed-status")
  private String detailedStatus = null;

  @SerializedName("links")
  private NsiLcmOpOccLinks links = null;

  public NsiLcmOpOcc _id(UUID _id) {
    this._id = _id;
    return this;
  }

   /**
   * Get _id
   * @return _id
  **/
  @Schema(description = "")
  public UUID getIdentifier() {
    return _id;
  }

  public void setIdentifier(UUID _id) {
    this._id = _id;
  }

  public NsiLcmOpOcc id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public NsiLcmOpOcc lcmOperationType(String lcmOperationType) {
    this.lcmOperationType = lcmOperationType;
    return this;
  }

   /**
   * Get lcmOperationType
   * @return lcmOperationType
  **/
  @Schema(description = "")
  public String getLcmOperationType() {
    return lcmOperationType;
  }

  public void setLcmOperationType(String lcmOperationType) {
    this.lcmOperationType = lcmOperationType;
  }

  public NsiLcmOpOcc netsliceInstanceId(UUID netsliceInstanceId) {
    this.netsliceInstanceId = netsliceInstanceId;
    return this;
  }

   /**
   * Get netsliceInstanceId
   * @return netsliceInstanceId
  **/
  @Schema(description = "")
  public UUID getNetsliceInstanceId() {
    return netsliceInstanceId;
  }

  public void setNetsliceInstanceId(UUID netsliceInstanceId) {
    this.netsliceInstanceId = netsliceInstanceId;
  }

  public NsiLcmOpOcc isAutomaticInvocation(Boolean isAutomaticInvocation) {
    this.isAutomaticInvocation = isAutomaticInvocation;
    return this;
  }

   /**
   * Get isAutomaticInvocation
   * @return isAutomaticInvocation
  **/
  @Schema(description = "")
  public Boolean isIsAutomaticInvocation() {
    return isAutomaticInvocation;
  }

  public void setIsAutomaticInvocation(Boolean isAutomaticInvocation) {
    this.isAutomaticInvocation = isAutomaticInvocation;
  }

  public NsiLcmOpOcc isCancelPending(Boolean isCancelPending) {
    this.isCancelPending = isCancelPending;
    return this;
  }

   /**
   * Get isCancelPending
   * @return isCancelPending
  **/
  @Schema(description = "")
  public Boolean isIsCancelPending() {
    return isCancelPending;
  }

  public void setIsCancelPending(Boolean isCancelPending) {
    this.isCancelPending = isCancelPending;
  }

  public NsiLcmOpOcc startTime(Float startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @Schema(description = "")
  public Float getStartTime() {
    return startTime;
  }

  public void setStartTime(Float startTime) {
    this.startTime = startTime;
  }

  public NsiLcmOpOcc statusEnteredTime(Float statusEnteredTime) {
    this.statusEnteredTime = statusEnteredTime;
    return this;
  }

   /**
   * Get statusEnteredTime
   * @return statusEnteredTime
  **/
  @Schema(description = "")
  public Float getStatusEnteredTime() {
    return statusEnteredTime;
  }

  public void setStatusEnteredTime(Float statusEnteredTime) {
    this.statusEnteredTime = statusEnteredTime;
  }

  public NsiLcmOpOcc operationParams(NsiLcmOpOccOperationParams operationParams) {
    this.operationParams = operationParams;
    return this;
  }

   /**
   * Get operationParams
   * @return operationParams
  **/
  @Schema(description = "")
  public NsiLcmOpOccOperationParams getOperationParams() {
    return operationParams;
  }

  public void setOperationParams(NsiLcmOpOccOperationParams operationParams) {
    this.operationParams = operationParams;
  }

  public NsiLcmOpOcc operationState(String operationState) {
    this.operationState = operationState;
    return this;
  }

   /**
   * Get operationState
   * @return operationState
  **/
  @Schema(description = "")
  public String getOperationState() {
    return operationState;
  }

  public void setOperationState(String operationState) {
    this.operationState = operationState;
  }

  public NsiLcmOpOcc detailedStatus(String detailedStatus) {
    this.detailedStatus = detailedStatus;
    return this;
  }

   /**
   * Get detailedStatus
   * @return detailedStatus
  **/
  @Schema(description = "")
  public String getDetailedStatus() {
    return detailedStatus;
  }

  public void setDetailedStatus(String detailedStatus) {
    this.detailedStatus = detailedStatus;
  }

  public NsiLcmOpOcc links(NsiLcmOpOccLinks links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @Schema(description = "")
  public NsiLcmOpOccLinks getLinks() {
    return links;
  }

  public void setLinks(NsiLcmOpOccLinks links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsiLcmOpOcc nsiLcmOpOcc = (NsiLcmOpOcc) o;
    return Objects.equals(this._id, nsiLcmOpOcc._id) &&
        Objects.equals(this.id, nsiLcmOpOcc.id) &&
        Objects.equals(this.lcmOperationType, nsiLcmOpOcc.lcmOperationType) &&
        Objects.equals(this.netsliceInstanceId, nsiLcmOpOcc.netsliceInstanceId) &&
        Objects.equals(this.isAutomaticInvocation, nsiLcmOpOcc.isAutomaticInvocation) &&
        Objects.equals(this.isCancelPending, nsiLcmOpOcc.isCancelPending) &&
        Objects.equals(this.startTime, nsiLcmOpOcc.startTime) &&
        Objects.equals(this.statusEnteredTime, nsiLcmOpOcc.statusEnteredTime) &&
        Objects.equals(this.operationParams, nsiLcmOpOcc.operationParams) &&
        Objects.equals(this.operationState, nsiLcmOpOcc.operationState) &&
        Objects.equals(this.detailedStatus, nsiLcmOpOcc.detailedStatus) &&
        Objects.equals(this.links, nsiLcmOpOcc.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, id, lcmOperationType, netsliceInstanceId, isAutomaticInvocation, isCancelPending, startTime, statusEnteredTime, operationParams, operationState, detailedStatus, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsiLcmOpOcc {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lcmOperationType: ").append(toIndentedString(lcmOperationType)).append("\n");
    sb.append("    netsliceInstanceId: ").append(toIndentedString(netsliceInstanceId)).append("\n");
    sb.append("    isAutomaticInvocation: ").append(toIndentedString(isAutomaticInvocation)).append("\n");
    sb.append("    isCancelPending: ").append(toIndentedString(isCancelPending)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    statusEnteredTime: ").append(toIndentedString(statusEnteredTime)).append("\n");
    sb.append("    operationParams: ").append(toIndentedString(operationParams)).append("\n");
    sb.append("    operationState: ").append(toIndentedString(operationState)).append("\n");
    sb.append("    detailedStatus: ").append(toIndentedString(detailedStatus)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
