/*
 * OSM NB API featuring ETSI NFV SOL005
 * This is Open Source MANO Northbound API featuring ETSI NFV SOL005. For more information on OSM, you can visit [http://osm.etsi.org](http://osm.etsi.org). You can send us your comments and questions to OSM_TECH@list.etsi.org or join the [OpenSourceMANO Slack Workplace](https://join.slack.com/t/opensourcemano/shared_invite/enQtMzQ3MzYzNTQ0NDIyLWVkNTE4ZjZjNWI0ZTQyN2VhOTI1MjViMzU1NWYwMWM3ODI4NTQyY2VlODA2ZjczMWIyYTFkZWNiZmFkM2M2ZDk) 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: OSM_TECH@list.etsi.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * NsiLcmOpOccOperationParams
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-04T13:03:17.599+01:00[Europe/Rome]")
public class NsiLcmOpOccOperationParams {
  @SerializedName("nsiName")
  private String nsiName = null;

  @SerializedName("nstId")
  private UUID nstId = null;

  @SerializedName("vimAccountId")
  private UUID vimAccountId = null;

  @SerializedName("netsliceInstanceId")
  private UUID netsliceInstanceId = null;

  @SerializedName("lcmOperationType")
  private String lcmOperationType = null;

  @SerializedName("nslcmops_ids")
  private List<UUID> nslcmopsIds = null;

  public NsiLcmOpOccOperationParams nsiName(String nsiName) {
    this.nsiName = nsiName;
    return this;
  }

   /**
   * Get nsiName
   * @return nsiName
  **/
  @Schema(description = "")
  public String getNsiName() {
    return nsiName;
  }

  public void setNsiName(String nsiName) {
    this.nsiName = nsiName;
  }

  public NsiLcmOpOccOperationParams nstId(UUID nstId) {
    this.nstId = nstId;
    return this;
  }

   /**
   * Get nstId
   * @return nstId
  **/
  @Schema(description = "")
  public UUID getNstId() {
    return nstId;
  }

  public void setNstId(UUID nstId) {
    this.nstId = nstId;
  }

  public NsiLcmOpOccOperationParams vimAccountId(UUID vimAccountId) {
    this.vimAccountId = vimAccountId;
    return this;
  }

   /**
   * Get vimAccountId
   * @return vimAccountId
  **/
  @Schema(description = "")
  public UUID getVimAccountId() {
    return vimAccountId;
  }

  public void setVimAccountId(UUID vimAccountId) {
    this.vimAccountId = vimAccountId;
  }

  public NsiLcmOpOccOperationParams netsliceInstanceId(UUID netsliceInstanceId) {
    this.netsliceInstanceId = netsliceInstanceId;
    return this;
  }

   /**
   * Get netsliceInstanceId
   * @return netsliceInstanceId
  **/
  @Schema(description = "")
  public UUID getNetsliceInstanceId() {
    return netsliceInstanceId;
  }

  public void setNetsliceInstanceId(UUID netsliceInstanceId) {
    this.netsliceInstanceId = netsliceInstanceId;
  }

  public NsiLcmOpOccOperationParams lcmOperationType(String lcmOperationType) {
    this.lcmOperationType = lcmOperationType;
    return this;
  }

   /**
   * Get lcmOperationType
   * @return lcmOperationType
  **/
  @Schema(description = "")
  public String getLcmOperationType() {
    return lcmOperationType;
  }

  public void setLcmOperationType(String lcmOperationType) {
    this.lcmOperationType = lcmOperationType;
  }

  public NsiLcmOpOccOperationParams nslcmopsIds(List<UUID> nslcmopsIds) {
    this.nslcmopsIds = nslcmopsIds;
    return this;
  }

  public NsiLcmOpOccOperationParams addNslcmopsIdsItem(UUID nslcmopsIdsItem) {
    if (this.nslcmopsIds == null) {
      this.nslcmopsIds = new ArrayList<UUID>();
    }
    this.nslcmopsIds.add(nslcmopsIdsItem);
    return this;
  }

   /**
   * Get nslcmopsIds
   * @return nslcmopsIds
  **/
  @Schema(description = "")
  public List<UUID> getNslcmopsIds() {
    return nslcmopsIds;
  }

  public void setNslcmopsIds(List<UUID> nslcmopsIds) {
    this.nslcmopsIds = nslcmopsIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsiLcmOpOccOperationParams nsiLcmOpOccOperationParams = (NsiLcmOpOccOperationParams) o;
    return Objects.equals(this.nsiName, nsiLcmOpOccOperationParams.nsiName) &&
        Objects.equals(this.nstId, nsiLcmOpOccOperationParams.nstId) &&
        Objects.equals(this.vimAccountId, nsiLcmOpOccOperationParams.vimAccountId) &&
        Objects.equals(this.netsliceInstanceId, nsiLcmOpOccOperationParams.netsliceInstanceId) &&
        Objects.equals(this.lcmOperationType, nsiLcmOpOccOperationParams.lcmOperationType) &&
        Objects.equals(this.nslcmopsIds, nsiLcmOpOccOperationParams.nslcmopsIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nsiName, nstId, vimAccountId, netsliceInstanceId, lcmOperationType, nslcmopsIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsiLcmOpOccOperationParams {\n");
    
    sb.append("    nsiName: ").append(toIndentedString(nsiName)).append("\n");
    sb.append("    nstId: ").append(toIndentedString(nstId)).append("\n");
    sb.append("    vimAccountId: ").append(toIndentedString(vimAccountId)).append("\n");
    sb.append("    netsliceInstanceId: ").append(toIndentedString(netsliceInstanceId)).append("\n");
    sb.append("    lcmOperationType: ").append(toIndentedString(lcmOperationType)).append("\n");
    sb.append("    nslcmopsIds: ").append(toIndentedString(nslcmopsIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
